export const ROLES = {
  ADMIN: "admin",
  DOCTOR: "doctor",
  RECORDS: "records",
  PATIENT: "patient",
};

export const USERS = {
  admin: {
    id: "USR001",
    name: "Rajesh Kumar",
    role: ROLES.ADMIN,
    email: "admin@lifeid.gov.in",
    password: "admin123",
    avatar: "RK",
  },
  doctor: {
    id: "USR002",
    name: "Dr. Priya Nair",
    role: ROLES.DOCTOR,
    email: "doctor@lifeid.gov.in",
    password: "doc123",
    avatar: "PN",
    hospital: "AIIMS New Delhi",
    phone: "+91 9876543210",
  },
  records: {
    id: "USR003",
    name: "Sanjay Mehta",
    role: ROLES.RECORDS,
    email: "records@lifeid.gov.in",
    password: "rec123",
    avatar: "SM",
    hospital: "AIIMS New Delhi",
    phone: "+91 8765432109",
  },
  patient: {
    id: "USR004",
    name: "Arjun Sharma",
    role: ROLES.PATIENT,
    email: "patient@lifeid.gov.in",
    password: "pat123",
    avatar: "AS",
    lifeId: "LID-IN-2024-00291",
  },
};

export const PATIENTS = [
  {
    id: "P001",
    lifeId: "LID-IN-2024-00291",
    name: "Arjun Sharma",
    dob: "1985-03-12",
    gender: "Male",
    phone: "+91 9876543210",
    bloodGroup: "O+",
    allergies: ["Penicillin", "Latex"],
    chronicDiseases: ["Hypertension", "Type 2 Diabetes"],
    medications: ["Metformin 500mg BD", "Lisinopril 10mg OD", "Aspirin 75mg OD"],
    emergencyContact: "+91 9988776655",
    address: "42, MG Road, Bengaluru, Karnataka 560001",
    lastUpdated: "2024-11-20",
    prescriptions: ["Rx-2024-11-20.pdf"],
    reports: ["Blood-Report-Oct.pdf"],
  },
  {
    id: "P002",
    lifeId: "LID-IN-2024-00147",
    name: "Sneha Iyer",
    dob: "1992-07-25",
    gender: "Female",
    phone: "+91 8765432109",
    bloodGroup: "A+",
    allergies: ["Sulfa drugs"],
    chronicDiseases: ["Asthma"],
    medications: ["Salbutamol inhaler PRN", "Montelukast 10mg OD"],
    emergencyContact: "+91 9876001234",
    address: "7, Anna Nagar, Chennai, Tamil Nadu 600040",
    lastUpdated: "2024-10-08",
    prescriptions: [],
    reports: [],
  },
  {
    id: "P003",
    lifeId: "LID-IN-2024-00388",
    name: "Rahul Verma",
    dob: "1970-01-15",
    gender: "Male",
    phone: "+91 7654321098",
    bloodGroup: "B-",
    allergies: [],
    chronicDiseases: ["Coronary Artery Disease"],
    medications: ["Aspirin 81mg OD", "Atorvastatin 40mg", "Bisoprolol 5mg OD"],
    emergencyContact: "+91 9765432100",
    address: "23, Civil Lines, Lucknow, Uttar Pradesh 226001",
    lastUpdated: "2024-12-01",
    prescriptions: ["Rx-2024-12-01.pdf"],
    reports: ["Echo-Report.pdf", "Stress-Test.pdf"],
  },
  {
    id: "P004",
    lifeId: "LID-IN-2024-00512",
    name: "Deepa Krishnan",
    dob: "2001-09-30",
    gender: "Female",
    phone: "+91 6543210987",
    bloodGroup: "AB+",
    allergies: ["Aspirin", "NSAIDs"],
    chronicDiseases: [],
    medications: ["Folic Acid 5mg OD"],
    emergencyContact: "+91 9870001234",
    address: "8, Salt Lake, Kolkata, West Bengal 700091",
    lastUpdated: "2024-09-15",
    prescriptions: [],
    reports: [],
  },
];

export const AUDIT_LOGS = [
  {
    id: "AL001",
    time: "2024-12-02 14:32:07",
    userId: "USR002",
    userName: "Dr. Priya Nair",
    role: "Doctor",
    hospitalId: "HOSP001",
    hospitalName: "AIIMS New Delhi",
    patientId: "P001",
    patientLid: "LID-IN-2024-00291",
    action: "Emergency Access",
    status: "Authorized",
  },
  {
    id: "AL002",
    time: "2024-12-02 11:15:44",
    userId: "USR003",
    userName: "Sanjay Mehta",
    role: "Records Officer",
    hospitalId: "HOSP001",
    hospitalName: "AIIMS New Delhi",
    patientId: "P002",
    patientLid: "LID-IN-2024-00147",
    action: "Record Update",
    status: "Authorized",
  },
  {
    id: "AL003",
    time: "2024-12-01 09:04:22",
    userId: "USR004",
    userName: "Arjun Sharma",
    role: "Patient",
    hospitalId: "—",
    hospitalName: "—",
    patientId: "P001",
    patientLid: "LID-IN-2024-00291",
    action: "Profile View",
    status: "Authorized",
  },
  {
    id: "AL004",
    time: "2024-11-30 16:50:11",
    userId: "USR005",
    userName: "Dr. Amit Gupta",
    role: "Doctor",
    hospitalId: "HOSP002",
    hospitalName: "Safdarjung Hospital",
    patientId: "P003",
    patientLid: "LID-IN-2024-00388",
    action: "Emergency Access",
    status: "Authorized",
  },
  {
    id: "AL005",
    time: "2024-11-29 08:22:33",
    userId: "UNKNOWN",
    userName: "Unknown",
    role: "—",
    hospitalId: "—",
    hospitalName: "—",
    patientId: "—",
    patientLid: "—",
    action: "Failed Login",
    status: "Denied",
  },
  {
    id: "AL006",
    time: "2024-11-28 13:10:05",
    userId: "USR003",
    userName: "Sanjay Mehta",
    role: "Records Officer",
    hospitalId: "HOSP001",
    hospitalName: "AIIMS New Delhi",
    patientId: "P001",
    patientLid: "LID-IN-2024-00291",
    action: "Patient Registration",
    status: "Authorized",
  },
];

export const HOSPITALS = [
  {
    id: "HOSP001",
    name: "AIIMS New Delhi",
    location: "New Delhi",
    officers: 42,
    contact: "+91 9876500001",
    status: "approved",
    applied: "2024-06-10",
  },
  {
    id: "HOSP002",
    name: "Safdarjung Hospital",
    location: "New Delhi",
    officers: 28,
    contact: "+91 9876500002",
    status: "approved",
    applied: "2024-07-22",
  },
  {
    id: "HOSP003",
    name: "KEM Hospital Mumbai",
    location: "Mumbai",
    officers: 35,
    contact: "+91 9876500003",
    status: "pending",
    applied: "2024-11-30",
  },
  {
    id: "HOSP004",
    name: "NIMHANS Bengaluru",
    location: "Bengaluru",
    officers: 0,
    contact: "+91 8765400004",
    status: "pending",
    applied: "2024-12-01",
  },
  {
    id: "HOSP005",
    name: "PGIMER Chandigarh",
    location: "Chandigarh",
    officers: 19,
    contact: "+91 7654300005",
    status: "approved",
    applied: "2024-09-05",
  },
];

export const MENUS = {
  admin: [
    { icon: "activity", label: "Overview", page: "overview" },
    { icon: "hospital", label: "Hospitals", page: "hospitals" },
    { icon: "users", label: "Users", page: "users" },
    { icon: "file", label: "Audit Logs", page: "logs" },
  ],
  doctor: [
    { icon: "activity", label: "Dashboard", page: "overview" },
    { icon: "fp", label: "Emergency Access", page: "emergency" },
    { icon: "bell", label: "Notifications", page: "notif" },
  ],
  records: [
    { icon: "activity", label: "Dashboard", page: "overview" },
    { icon: "plus", label: "Register Patient", page: "register" },
    { icon: "search", label: "Search Records", page: "search" },
    { icon: "edit", label: "Update Records", page: "update" },
  ],
  patient: [
    { icon: "id", label: "My Profile", page: "overview" },
    { icon: "lock", label: "Medical Records", page: "medical" },
    { icon: "qr", label: "LifeID Card", page: "qrcard" },
    { icon: "clock", label: "Access History", page: "history" },
    { icon: "phone", label: "Update Contact", page: "contact" },
  ],
};

export const ROLE_LABELS = {
  admin: "System Admin",
  doctor: "Medical Officer",
  records: "Records Officer",
  patient: "Patient",
};

export const ROLE_COLORS = {
  admin: "#7c3aed",
  doctor: "#2563eb",
  records: "#059669",
  patient: "#dc2626",
};
